global:
  scrape_interval: "10s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets:
        - "localhost:9090"
  - job_name: "pushgateway"
    honor_labels: true
    static_configs:
    - targets:
        - "localhost:9091"
  - job_name: "alertmanager"
    static_configs:
    - targets:
        - "localhost:9093"
  - job_name: "node"
    static_configs:
    - targets:
        - "localhost:9100"
   - job_name: "blackbox"
     static_configs:
     - targets:
         - "localhost:9115"
   - job_name: 'iptv'
     metrics_path: /probe
     params:
       module: [http_2xx]
     file_sd_configs:
       - files:
           - '/etc/prometheus/blackbox/iptv.yml'
    relabel_configs:
       - source_labels: [__address__]
         target_label: __param_target
       - source_labels: [__param_target]
         target_label: instance
       - target_label: __address__
         replacement: 127.0.0.1:9115  # Blackbox exporter.

